<?php
# 2024-05-06
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Theme/templates/homepage.phtml`":
# https://github.com/cabinetsbay/core/issues/8
# 2024-05-23
# "Refactor the «Popular RTA Cabinet Styles» home page block as a widget": https://github.com/cabinetsbay/catalog/issues/27
use CabinetsBay\Catalog\Category\Attribute as A;
use Magento\Catalog\Model\Category as C;
use Magento\Catalog\Model\ResourceModel\Category\Collection as CC;
/**
 * 2024-05-23
 * @see \CabinetsBay\Catalog\B\Featured::p()
 * @var int[] $categoryIds
 * @var string $cmsBlockId
 */
if (count(
	$cc = df_category_c($categoryIds)
		->addAttributeToSelect([A::DOOR_SAMPLE_LINK, A::KITCHEN_PRICE, A::KITCHEN_SET, 'image', 'name'])
		->joinUrlRewrite()
)) { /** @var CC $cc */ ?>
	<div class="homepage-popular c-products-grid">
		<?= df_cms_block($cmsBlockId) ?>
		<ul>
		<?php foreach ($cc as $c) {/** @var C $c */ ?>
			<li>
				<a href='<?= $c->getUrl() ?>'>
					<div><?= $c->getName() ?></div>
					<?php if ($ks = $c[A::KITCHEN_SET]) { ?>
						<div class='size-price'><b><?= $ks ?></b><?= $c[A::KITCHEN_PRICE] ?></div>
					<?php } ?>
					<img border='0' src='<?= $c->getImageUrl() ?>' />
				</a>
				<div>
					<a href='<?= $c->getUrl() ?>'>Shop cabinets</a>
					<a href='<?= $c[A::DOOR_SAMPLE_LINK] ?>'>Order sample</a>
				</div>
			</li>
		<?php } ?>
		</ul>
	</div>
<?php
}