<?php
# 2024-06-17
# "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
use CabinetsBay\Catalog\B\Products as B;
use Magento\Catalog\Model\Product as P;
/** @var B $b */
?>
<ol class="products list items product-items">
	<?php
	foreach ($b->getLoadedProductCollection() as $p) { /** @var P $p */
		echo df_block_output('CabinetsBay_Catalog', 'products/not-empty/ol/product', ['b' => $b, 'p' => $p]);
	} ?>
</ol>