<?php
# 2024-06-17
# "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
use CabinetsBay\Catalog\B\Products as B;
use Magento\Catalog\Model\Product as P;
/** @var B $b */
echo df_tag('ol', 'products list items product-items', df_cc_n(df_map(function(P $p) use($b):string {return df_block_output(
	'CabinetsBay_Catalog', 'products/not-empty/ol/product', ['b' => $b, 'p' => $p]
);}, $b->getLoadedProductCollection())));