<?php
# 2024-06-17
# 1) "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
# 2) "The frontend product list pages should show products as a list on narrow screens and as a grid on wide screens":
# https://github.com/cabinetsbay/catalog/issues/40
# 2024-06-27
# "Products are wrongly displayed on frontend category pages on narrow screens": https://github.com/cabinetsbay/catalog/issues/42
# 2024-09-12
# "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products/not-empty/product.phtml`":
# https://github.com/cabinetsbay/catalog/issues/51
use CabinetsBay\Catalog\B\Products as B;
use Magento\Catalog\Block\Product\ReviewRendererInterface as IReviewRenderer;
use Magento\Catalog\Model\Product as P;
use Magento\Framework\App\Action\Action;
/** @var B $b */ /** @var P $p */
$pos = $b['positioned'];
?>
<li class="item product product-item">
	<div class="product-item-info" data-container='product-grid'>
		<?php
		$productImage = $b->getImage($p, 'category_page_list');
		if ($pos != null) {
			$position = ' style="left:'
				. $productImage->getWidth() . 'px;'
				. 'top:' . $productImage->getHeight()
				. 'px;"';
		}
		?>
		<?php $pNameStripped = $b->stripTags($p->getName(), null, true); ?>
		<strong class="product name product-item-name product-item-name-second">
			<a
				class="product-item-link"
				href="<?= $p->getProductUrl() ?>">
				<?= df_product_att_html($p, $p->getName(), 'name') ?>
			</a>
		</strong>
		<a
			class="product photo product-item-photo"
			href="<?= $p->getProductUrl() ?>"
			tabindex="-1"
		><?= $productImage->toHtml() ?></a>
		<div class="product details product-item-details">
			<?php $pNameStripped = $b->stripTags($p->getName(), null, true); ?>
			<strong class="product name product-item-name">
				<a
					class="product-item-link"
					href="<?= $p->getProductUrl() ?>"
				><?= df_product_att_html($p, $p->getName(), 'name') ?></a>
			</strong>
			<?= $b->getReviewsSummaryHtml($p, IReviewRenderer::FULL_VIEW) ?>
			<div class="product description product-item-description">
				<?= df_product_att_html($p, $p->getShortDescription(), 'short_description') ?>
				<a
					href="<?= $p->getProductUrl() ?>"
					title="<?= $pNameStripped ?>"
					class="action more"
				>Learn More</a>
			</div>
			<?= $b->getProductPrice($p) ?>
			<?= $b->getProductDetailsHtml($p) ?>
			<div class="product-item-inner">
				<div class="product actions product-item-actions"<?= strpos($pos, 'grid-actions') ? $position : '' ?>>
					<div class="actions-primary"<?= strpos($pos, 'grid-primary') ? $position : '' ?>>
						<?php if ($p->isSaleable()): ?>
							<?php $postParams
								= $b->getAddToCartPostParams($p); ?>
							<form data-role="tocart-form"
								  data-product-sku="<?= $b->escapeHtml($p->getSku()) ?>"
								  action="<?= $postParams['action'] ?>"
								  method="post">
								<input type="hidden"
									   name="product"
									   value="<?=
									   $postParams['data']['product'] ?>">
								<input type="hidden"
									   name="<?=
									   Action::PARAM_NAME_URL_ENCODED ?>"
									   value="<?=
									   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
								<?= $b->getBlockHtml('formkey') ?>
								<?php $qty = ($b->getProductDefaultQty() == 0) ? 1 :
								 $b->getProductDefaultQty(); ?>
								<input type="number"
									   name="qty"
									   maxlength="4"
									   value="<?php  echo $qty ?>"
									   title="<?php  echo __('Qty') ?>" class="input-text qty form-control"
									   data-validate="<?php echo $b->escapeHtml(json_encode($b->getQuantityValidators())) ?>"
								/>
								<button type="submit"
										title="<?= $b->escapeHtml(__('Add to Cart')) ?>"
										class="action tocart primary">
									<span><?= __('Add to Cart') ?></span>
								</button>
							</form>
						<?php else: ?>
							<?php if ($p->isAvailable()): ?>
								<div class="stock available">
									<span><?= __('In stock') ?></span>
								</div>
							<?php else: ?>
								<div class="stock unavailable">
									<span><?= __('Out of stock') ?></span>
								</div>
							<?php endif; ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</li>