<?php
# 2024-03-10
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/catalog/issues/22
use CabinetsBay\Catalog\B\Category as B;
/** @var B $block */ $b = $block; /** @var B $b */
# 2024-03-10
# 2.1) Level 0: «Root Catalog».
# 2.2) Level 1: «Default Category».
# 2.3) Level 2:
# 		«Ready to Assemble Cabinets»
# 		«Pre-Assembled Cabinets»
# 		«Cabinet Organizers & Hardware»
# 2.4) Level 3: «Steam White Shaker».
if (cb_category_is_l2()) {
	?><h1 class="page-title"><?= df_category_current()->getName(); ?></h1><?php
}
else {
	# 2024-03-11
	# 1) "The `H1` tag is duplicated on the frontend category pages": https://github.com/cabinetsbay/catalog/issues/23
	# 2) "Category names are not shown on narrow screens": https://github.com/cabinetsbay/catalog/issues/20
	echo $b->title();
	echo df_block_output('CabinetsBay_Catalog', 'category/l3/tabs', ['b' => $b]);
}
if ($b->isContentMode() || $b->isMixedMode()) {
	?><div class="category-cms"><?= $b->getCmsBlockHtml() ?></div><?php
}