<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use CabinetsBay\Catalog\Category\Attribute as A;
use Magento\Catalog\Model\Category as C;
/** @var C $c */
?>
<a href='<?= $c->getUrl() ?>'>
	<div><?= $c->getName() ?></div>
	<?php if ($set = $c[A::KITCHEN_SET]) { ?>
		<div class='size-price'>
			<b><?= $set ?></b><?= $c[A::KITCHEN_PRICE] ?>
		</div>
	<?php } ?>
	<img border='0' src='<?= $c->getImageUrl() ?>'/>
</a>
<div>
	<a href='<?= $c->getUrl() ?>'>Shop cabinets</a>
	<a href='<?= $c[A::DOOR_SAMPLE_LINK] ?>'>Order sample</a>
</div>