<?php
# 2024-06-17
# "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
use CabinetsBay\Catalog\B\Products as B;
use Magento\Catalog\Model\Product as P;
/** @var B $b */
echo $b->getToolbarHtml() . $b->getAdditionalHtml();
# 2024-06-17
# "The frontend product list pages should show products as a list on narrow screens and as a grid on wide screens":
# https://github.com/cabinetsbay/catalog/issues/40
# 2024-06-27
# "Products are wrongly displayed on frontend category pages on narrow screens": https://github.com/cabinetsbay/catalog/issues/42
echo df_tag('div',
	df_cc_s('products', 'wrapper', 'grid', 'products-grid')
	,df_cc_n(
		# 2024-03-10
		# 1.1) Level 0: «Root Catalog».
		# 1.2) Level 1: «Default Category».
		# 1.3) Level 2:
		# 		«Ready to Assemble Cabinets»
		# 		«Pre-Assembled Cabinets»
		# 		«Cabinet Organizers & Hardware»
		# 2024-06-10
		# 1) "Handle category levels > 3": https://github.com/cabinetsbay/catalog/issues/36
		# 2.1) Level 4: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets.html
		# 2.2) Level 5: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets/pantry-cabinets.html
		3 === df_category_level() ? '' : df_tag('h3', [], df_category_current()->getName())
		,df_tag('ol', 'products list items product-items', df_cc_n(df_map(function(P $p) use($b):string {return df_block_output(
			'CabinetsBay_Catalog', 'products/not-empty/product', ['b' => $b, 'p' => $p]
		);}, $b->getLoadedProductCollection())))
	)
);
echo $b->getChildBlock('toolbar')->setIsBottom(true)->toHtml();
if (!$b->isRedirectToCartEnabled()) {
	$lastProduct = df_last($b->getLoadedProductCollection()); /** @var P $lastProduct */
	echo df_js_x('[data-role=tocart-form], .form.map.checkout', '', 'catalogAddToCart', ['product_sku' => $lastProduct->getSku()]);
}