<?php
# 2024-06-17
# "Refactor `vendor/cabinetsbay/catalog/view/frontend/templates/products.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
use CabinetsBay\Catalog\B\Products as B;
/** @var B $b */
echo $b->getToolbarHtml() . $b->getAdditionalHtml();
# 2024-06-17
# "The frontend product list pages should show products as a list on narrow screens and as a grid on wide screens":
# https://github.com/cabinetsbay/catalog/issues/40
$viewMode = 'list';
?>
<div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
	<?php
		/**
		 * 2024-03-10
		 * 1.1) Level 0: «Root Catalog».
		 * 1.2) Level 1: «Default Category».
		 * 1.3) Level 2:
		 * 		«Ready to Assemble Cabinets»
		 * 		«Pre-Assembled Cabinets»
		 * 		«Cabinet Organizers & Hardware»
		 * 2024-06-10
		 * 1) "Handle category levels > 3": https://github.com/cabinetsbay/catalog/issues/36
		 * 2.1) Level 4: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets.html
		 * 2.2) Level 5: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets/pantry-cabinets.html
		 */
		if (3 < df_category_level()) { ?>
			<h3><?= df_category_current()->getName(); ?></h3>
		<?php }
			echo df_block_output('CabinetsBay_Catalog', 'products/not-empty/ol', ['b' => $b]);
		?>
</div>
<?= $b->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
<?php if (! $b->isRedirectToCartEnabled()) : ?>
	<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				"product_sku": "<?= /* @NoEscape */
		$_product->getSku() ?>"
			}
		}
	}
	</script>
<?php endif; ?>