<?php
# 2024-03-14
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/catalog/issues/18
use CabinetsBay\Catalog\B\Category as B;
/** @var B $b */
# 2024-09-02 https://3v4l.org/NNHbU
df_block_echo($b, 'category/l2/l3', [
	'cc' => df_category_children($b->getCurrentCategory())->setOrder('position', 'ASC')
])('filters', 'items');