<?php
# 2024-03-14
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/catalog/issues/18
use Magento\Catalog\Model\ResourceModel\Category\Collection as CC;
use CabinetsBay\Catalog\B\Category as B;
/** @var B $b */
$cc = df_category_children($b->getCurrentCategory())->setOrder('position', 'ASC'); /** @var CC $cc */
$echo = df_block_echo('CabinetsBay_Catalog', 'category/l2/l3', ['cc' => $cc]);
$echo('filters', 'items');