<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/catalog/issues/22
use CabinetsBay\Catalog\Category\Attribute as A;
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
echo $b->l3a(A::STYLES);
if (count($cc = $b->l3p())) { /** @var C[] $cc */ ?>
	<div class='c-products-grid'>
		<ul>
			<?php foreach ($cc as $c) {/** @var C $c */ ?>
				<li>
					<?= df_block_output('CabinetsBay_Catalog', 'category/item', ['c' => $c]) ?>
				</li>
			<?php } ?>
		</ul>
	</div>
	<?php
}