<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/catalog/issues/22
use Magento\Catalog\Model\Category as C;
use CabinetsBay\Catalog\B\Category as B; /** @var B $b */
df_assert($l3 = $b->l3()); /** @var C $l3 */
?>
<div class='category-info'>
	<div class='cb-gallery'>
		<?php
		/**
		 * 2024-06-09
		 * $ii:
		 * 	{
		 * 		"3628/swuc_1.jpg": "Croydon White Shaker Ready to Assemble Cabinets",
		 * 		"3628/swuc_1_1.jpg": "Croydon White Shaker Ready to Assemble Cabinets in Philadelphia",
		 * 		"3628/swuc_2.jpg": "best Croydon White Shaker Ready to Assemble Cabinets ",
		 * 		"3628/swuc_2_1.jpg": "Door Sample Croydon White Shaker Ready to Assemble Cabinets",
		 * 		"3628/swuc_3.jpg": "Croydon White Shaker Ready to Assemble Cabinets for kitchen island",
		 * 		"3628/swuc_4.jpg": "Croydon White Shaker Ready to Assemble Cabinets for office",
		 * 		"3628/swuc_5.jpg": "Bathroom Croydon White Shaker Ready to Assemble Cabinets",
		 * 		"3628/swuc_5_7.jpg": "Bathroom Croydon White Shaker Cabinets"
		 *	 }
		 * @var array(string => string) $ii
		 */
		if ($ii = $b->images()) { ?>
			<ul id='category-gallery' class='gallery list-unstyled cS-hidden'>
				<?=
					df_cc_n(df_map_k($ii, function(string $f, string $t):string {return
						df_tag('li', [
							'data-src' => $u = df_media_path2url("wysiwyg/catalog-carousel-images/$f")
							,'data-thumb' => $u
						], df_tag('img', ['alt' => $t,'src' => $u, 'title' => $t]))
					;}))
				?>
			</ul>
			<script>
				require(['jquery', 'domReady!'], function($) {
					let totalWidth = 0;
					$('.owl-thumb-item').each(function() {
						totalWidth += parseInt($(this).width(), 10);
					});
					$('.owl-thumbs').css('width', (totalWidth + 20)+'px');
				});
			</script>
		<?php }
		else {
			try {
				if ($url = $l3->getImageUrl()) {
					echo df_category_att_html(
						$l3
						,df_tag('div', 'category-image', df_tag('img', [
							'alt' => $l3->getName()
							,'class' => 'image'
							,'src' => $url
							,'title' => $l3->getName()
						]))
						,'image'
					);
				}
			} catch (\Magento\Framework\Exception\LocalizedException $e) {}
		}
		?>
	</div>
	<div class="cb-text">
		<?php if ($_description = $l3->getDescription()): ?>
			<div class="category-description">
				<?= df_category_att_html($l3, $_description, 'description') ?>
			</div>
		<?php endif; ?>
		<div class="category-subdescription">
			<div class="table-view">
				<a href="/sample-doors.html">Order Sample</a>
				<a href="/kitchen-design-assistance.html">Free Design</a>
			</div>
			<a class="scrollTo" href="#layer-product-list">Shop Cabinets Below <i></i></a>
		</div>
	</div>
</div>